controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_suite_web:
    path: /suiteWeb
    controller: App\Controller\SuiteWebController::index
manager:
    path: /manager
    controller: App\Controller\ManagerController::index

activty:
    path: /activty
    controller: App\Controller\ActivtyController::index




